apiVersion: v2
name: drone
version: 0.0.1
description: A Helm wrapper chart for drone
type: application
sources:
  - https://charts.drone.io
dependencies: # A list of the chart requirements (optional)
  - name: drone
    version: 0.6.4
    repository: https://charts.drone.io
